export const LOAD_ALL_ACCIDENTS_COORDS_START = 'LOAD_ALL_ACCIDENTS_COORDS_START';
export const LOAD_ALL_ACCIDENTS_COORDS_SUCCESS = 'LOAD_ALL_ACCIDENTS_COORDS_SUCCESS';
export const LOAD_ALL_ACCIDENTS_COORDS_ERROR = 'LOAD_ALL_ACCIDENTS_COORDS_ERROR';

export const SHOW_ALL_ACCIDENTS = 'SHOW_ALL_ACCIDENTS';
export const HIDE_ALL_ACCIDENTS = 'HIDE_ALL_ACCIDENTS';

export const GET_NEAREST_ACCIDENT_START = 'GET_NEAREST_ACCIDENT_START';
export const GET_NEAREST_ACCIDENT_SUCCESS = 'GET_NEAREST_ACCIDENT_SUCCESS';
export const GET_NEAREST_ACCIDENT_ERROR = 'GET_NEAREST_ACCIDENT_ERROR';

export const FIND_ACCIDENTS_WITHIN_POLYGON_START = 'FIND_ACCIDENTS_WITHIN_POLYGON_START';
export const FIND_ACCIDENTS_WITHIN_POLYGON_SUCCESS = 'FIND_ACCIDENTS_WITHIN_POLYGON_SUCCESS';
export const FIND_ACCIDENTS_WITHIN_POLYGON_ERROR = 'FIND_ACCIDENTS_WITHIN_POLYGON_ERROR';
