export const LOAD_ALL_ACCIDENTS_COORDS_START = 'LOAD_ALL_ACCIDENTS_COORDS_START';
export const LOAD_ALL_ACCIDENTS_COORDS_SUCCESS = 'LOAD_ALL_ACCIDENTS_COORDS_SUCCESS';
export const LOAD_ALL_ACCIDENTS_COORDS_ERROR = 'LOAD_ALL_ACCIDENTS_COORDS_ERROR';

export const SHOW_ALL_ACCIDENTS = 'SHOW_ALL_ACCIDENTS';
export const HIDE_ALL_ACCIDENTS = 'HIDE_ALL_ACCIDENTS';