export const LOAD_ALL_ACCIDENTS_COORDS_START = 'LOAD_ALL_ACCIDENTS_COORDS_START';
export const LOAD_ALL_ACCIDENTS_COORDS_SUCCESS = 'LOAD_ALL_ACCIDENTS_COORDS_SUCCESS';
export const LOAD_ALL_ACCIDENTS_COORDS_ERROR = 'LOAD_ALL_ACCIDENTS_COORDS_ERROR';